### PR TITLE
include README.md in sdist

### PR DESCRIPTION
**Pull request by dotlambda**
Otherwise build fails with
```
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```
It would be nice if you could make a new release that includes `README.md`.

### CODE REVIEW

**Comment by zadacka** [comment]
Agreed - this is referenced in setup.py so needs to be in the manifest or causes problems at build time.

**Comment by zadacka** [comment]
Turns out that I needed  to add the README.md entry as an `include` command to the manually created MANIFEST.in
... rather than adding it to the automatically created MANIFEST file.

This seems to be okay (I've just used it to build a new version of easygui, v0.98.3). Please let me know if you spot any issues...

**Comment by dotlambda** [comment]
Thank you, it works flawlessly!

**Comment by zadacka** [comment]
Thank you for confirming (and for your patience)! 😅

**Pull request merged**
