### PR TITLE
Update text_box.py

### PR DESCRIPTION
**Pull request by doyousketch2**
Reduces some of the extraneous padding around textboxes,
underneath the message, especially.

### CODE REVIEW

**Comment by spyoungtech** [comment]
I find it interesting that you find it optimal to remove padding from the text box. I opened an issue because there was not *enough* padding on messages, particularly on the bottom. This is particularly evident when word wrapping occurs. See issue #114 for screenshots and #115 for my proposed fix.

**Comment by doyousketch2** [comment]
Normally the message in the header has way too much space around it.
(and you'd only see 25 lines of text)
Here's a Pic

**Comment by doyousketch2** [comment]
Here's the normal squat padding.
Here's a Pic

**Comment by spyoungtech** [comment]
Gotcha now! I was confused there for a moment because `button_box.py` implements a Text widget and I looked at the code without looking at what file we were talking about. I should learn to read, or something.

**Pull request merged**
