### PR TITLE
Fixed a bug in choice_box.py which crashed Python 3

### PR DESCRIPTION
**Pull request by thomas-haslwanter**
Minor change in the format for raising exceptions. I was surprised this has not come up previously!
Eliminated test_case "weather_man.py", because it had to connection to easygui
Fixed a Python3- incompatability in test_cases/file_open_box.py (braces for call to "print")

### CODE REVIEW

**Comment by mjpieters** [comment]
This is issue #97, the pull request duplicates #100.

**Comment by thomas-haslwanter** [comment]
Seems that this change has been incorporated in the meantime, so I close the PR.

**Comment by jjdenis** [comment]
But what about the other proposed changes? Do you mind if I open and merge them?

**Comment by thomas-haslwanter** [comment]
This is ok with me.
From my point of view, the biggest remaining problem is that the current version on PyPi has not been updated to use the current version of easygui on github.

I don’t have the rights to do so.

Thanks
thomas

Von: Juan José Denis Corrales [mailto:notifications@github.com]
Gesendet: Monday, 26 September, 2016 11:05 PM
An: robertlugg/easygui <easygui@noreply.github.com>
Cc: Haslwanter Thomas <Thomas.Haslwanter@fh-linz.at>; State change <state_change@noreply.github.com>
Betreff: Re: [robertlugg/easygui] Fixed a bug in choice_box.py which crashed Python 3 (#103)


But what about the other proposed changes? Do you mind if I open and merge them?

**Pull request merged**
